=== IslasGECI/starwars_kata/tests/swapi-planets-schema.json
{
    "$schema": "http://json-schema.org/2020-12/schema",
    "type": "object",
    "properties": {
        "name": {
            "type": "string"
        },
        "climate": {
            "type": "string"
        },
        "created": {
            "type": "string"
        },
        "diameter": {
            "type": "string"
        },
        "edited": {
            "type": "string"
        },
        "films": {
            "type": "array",
            "items": [
                {
                    "type": "string"
                }
            ]
        },
        "gravity": {
            "type": "string"
        },
        "orbital_period": {
            "type": "string"
        },
        "population": {
            "type": "string"
        },
        "residents": {
            "type": "array",
            "items": {}
        },
        "rotation_period": {
            "type": "string"
        },
        "surface_water": {
            "type": "string"
        },
        "terrain": {
            "type": "string"
        },
        "url": {
            "type": "string"
        }
    },
    "required": [
        "name",
        "climate",
        "created",
        "diameter",
        "edited",
        "films",
        "gravity",
        "orbital_period",
        "population",
        "residents",
        "rotation_period",
        "surface_water",
        "terrain",
        "url"
    ]
}

=== IslasGECI/starwars_kata/tests/expected-planets.json
{   "name": "Yavin IV",
    "climate": "temperate, tropical",
    "created": "2014-12-10T11:37:19.144000Z",
    "diameter": "10200",
    "edited": "2014-12-20T20:58:18.421000Z",
    "films": [
        "https://swapi.dev/api/films/1/"
    ],
    "gravity": "1 standard",
    "orbital_period": "4818",
    "population": "1000",
    "residents": [],
    "rotation_period": "24",
    "surface_water": "8",
    "terrain": "jungle, rainforests",
    "url": "https://swapi.dev/api/planets/3/"
}
